
const certsTemplate = [
    { path: "3C.svg", name: "Chứng nhận bắt buộc Trung Quốc (China Compulsory Certificate)" },
    { path: "5S.svg", name: "Chứng nhận 5S" },
    { path: "BCT_blue.svg", name: "Chứng nhận đã thông báo Bộ Công Thương (Việt Nam)" },
    { path: "BCT_red.svg", name: "Chứng nhận đã đăng ký Bộ Công Thương (Việt Nam)" },
    { path: "BRCGS.svg", name: "Chứng nhận tiêu chuẩn toàn cầu về an toàn thực phẩm của Tổ chức Tiêu chuẩn Anh Quốc (British Retail Consortium Global Standard)" },
    { path: "BREEAM.svg", name: "Chứng chỉ đánh giá môi trường BREEAM (Building Research Establishment Environmental Assessment Method)" },
    { path: "CarbonTrustStandard.svg", name: "Chứng nhận Carbon Trust Standard" },
    { path: "CEMarking.svg", name: "Chứng nhận CE Marking (Châu Âu)" },
    { path: "CEV.svg", name: "Chứng nhận CEV (Chứng nhận năng lượng tái tạo)" },
    { path: "ChungNhanHuuCo_vn.svg", name: "Chứng nhận hữu cơ Việt Nam" },
    { path: "CRS.svg", name: "Chứng nhận CRS (Corporate Social Responsibility)" },
    { path: "EAC.svg", name: "Chứng nhận EAC (Liên minh Kinh tế Á-Âu)" },
    { path: "ECOCERT.svg", name: "Chứng nhận hữu cơ của tổ chức ECOCERT" },
    { path: "ENECMark.svg", name: "Chứng nhận ENEC Mark (Châu Âu)" },
    { path: "EnergyStar.svg", name: "Chứng nhận Energy Star (Mỹ)" },
    { path: "EPEAT.svg", name: "Chứng nhận EPEAT (Electronic Product Environmental Assessment Tool)" },
    { path: "Fairmined.svg", name: "Chứng nhận Fairmined (Vàng khai thác thủ công và khai thác quy mô nhỏ)" },
    { path: "FairTrade.svg", name: "Chứng nhận Thương mại công bằng (Fair Trade)" },
    { path: "FCC.svg", name: "Chứng nhận FCC (Ủy ban Truyền thông Liên bang Mỹ)" },
    { path: "FDAApproval.svg", name: "Chứng nhận FDA (Cục Quản lý Thực phẩm và Dược phẩm Hoa Kỳ)" },
    { path: "FSC.svg", name: "Chứng nhận FSC (Forest Stewardship Council)" },
    { path: "FSSC22000.svg", name: "Chứng nhận FSSC 22000 (Hệ thống quản lý an toàn thực phẩm)" },
    { path: "GFSI.svg", name: "Chứng nhận GFSI (Sáng kiến An toàn Thực phẩm Toàn cầu)" },
    { path: "GlobalG.A.P..svg", name: "Chứng nhận GlobalG.A.P. (Thực hành nông nghiệp tốt toàn cầu)" },
    { path: "GMP.svg", name: "Chứng nhận GMP (Thực hành sản xuất tốt)" },
    { path: "GOTS.svg", name: "Chứng nhận GOTS (Tiêu chuẩn Toàn cầu về Dệt hữu cơ)" },
    { path: "GREENGUARD.svg", name: "Chứng nhận GREENGUARD (Chất lượng không khí trong nhà)" },
    { path: "HACCP.svg", name: "Chứng nhận HACCP (Phân tích mối nguy và Điểm kiểm soát quan trọng)" },
    { path: "Halal.svg", name: "Chứng nhận Halal" },
    { path: "HVNCLC.svg", name: "Chứng nhận hàng Việt Nam chất lượng cao" },
    { path: "IEC17025.svg", name: "Chứng nhận ISO/IEC 17025 (Yêu cầu chung về năng lực của phòng thí nghiệm thử nghiệm và hiệu chuẩn)" },
    { path: "IFS.svg", name: "Chứng nhận IFS (International Featured Standards)" },
    { path: "ISO.svg", name: "Chứng nhận ISO (Tổ chức Tiêu chuẩn hóa Quốc tế)" },
    { path: "KosherCertification.svg", name: "Chứng nhận Kosher" },
    { path: "LEEDCertification.svg", name: "Chứng nhận LEED (Lãnh đạo trong Thiết kế và Xây dựng Sinh thái)" },
    { path: "LOGO_VIETNAM ECO LABEL.svg", name: "Chứng nhận nhãn sinh thái Việt Nam" },
    { path: "MSC.svg", name: "Chứng nhận MSC (Marine Stewardship Council)" },
    { path: "NFC.svg", name: "Chứng nhận NFC (Near Field Communication)" },
    { path: "NFPA.svg", name: "Chứng nhận NFPA (Hiệp hội Phòng cháy chữa cháy Quốc gia Mỹ)" },
    { path: "OCOP.svg", name: "Chứng nhận OCOP (Chương trình mỗi xã một sản phẩm)" },
    { path: "OEKOTEXStandard100.svg", name: "Chứng nhận Oeko-Tex Standard 100 (Vật liệu dệt không gây hại cho sức khỏe)" },
    { path: "OrganicCertification.svg", name: "Chứng nhận hữu cơ" },
    { path: "PEFC.svg", name: "Chứng nhận PEFC (Programme for the Endorsement of Forest Certification)" },
    { path: "REACHCompliance.svg", name: "Tuân thủ quy định REACH (Đăng ký, Đánh giá, Cho phép và Hạn chế Hóa chất)" },
    { path: "RoHS.svg", name: "Chứng nhận RoHS (Hạn chế sử dụng một số chất nguy hiểm trong thiết bị điện và điện tử)" },
    { path: "RSPO.svg", name: "Chứng nhận RSPO (Roundtable on Sustainable Palm Oil)" },
    { path: "TCVN.svg", name: "Tiêu chuẩn Việt Nam (TCVN)" },
    { path: "ULCertification.svg", name: "Chứng nhận UL (Underwriters Laboratories)" },
    { path: "VietGAHP (Vietnamese Good Animal Husbandry Practices).svg", name: "Chứng nhận VietGAHP (Thực hành chăn nuôi tốt Việt Nam)" },
    { path: "VietGAP (Vietnamese Good Agricultural Practices).svg", name: "Chứng nhận VietGAP (Thực hành nông nghiệp tốt Việt Nam)" }
];

export default certsTemplate;