
const certsTemplate = [
    {shortname: "3C", path: "3C.svg", name: "Chứng nhận bắt buộc Trung Quốc (China Compulsory Certificate)" },
    {shortname: "5S", path: "5S.svg", name: "Chứng nhận 5S" },
    {shortname: "Bộ công thương", path: "BCT_blue.svg", name: "Chứng nhận đã thông báo Bộ Công Thương (Việt Nam)" },
    {shortname: "Bộ công thương", path: "BCT_red.svg", name: "Chứng nhận đã đăng ký Bộ Công Thương (Việt Nam)" },
    {shortname: "BRCGS", path: "BRCGS.svg", name: "Chứng nhận tiêu chuẩn toàn cầu về an toàn thực phẩm của Tổ chức Tiêu chuẩn Anh Quốc (British Retail Consortium Global Standard)" },
    {shortname: "BREEAM", path: "BREEAM.svg", name: "Chứng chỉ đánh giá môi trường BREEAM (Building Research Establishment Environmental Assessment Method)" },
    {shortname: "Carbon Trust", path: "CarbonTrustStandard.svg", name: "Chứng nhận Carbon Trust Standard" },
    {shortname: "CE", path: "CEMarking.svg", name: "Chứng nhận CE Marking (Châu Âu)" },
    {shortname: "CEV", path: "CEV.svg", name: "Chứng nhận CEV (Chứng nhận năng lượng tái tạo)" },
    {shortname: "hữu cơ Việt Nam", path: "ChungNhanHuuCo_vn.svg", name: "Chứng nhận hữu cơ Việt Nam" },
    {shortname: "CRS", path: "CRS.svg", name: "Chứng nhận CRS (Corporate Social Responsibility)" },
    {shortname: "EAC", path: "EAC.svg", name: "Chứng nhận EAC (Liên minh Kinh tế Á-Âu)" },
    {shortname: "ECOCERT", path: "ECOCERT.svg", name: "Chứng nhận hữu cơ của tổ chức ECOCERT" },
    {shortname: "ENEC Mark", path: "ENECMark.svg", name: "Chứng nhận ENEC Mark (Châu Âu)" },
    {shortname: "Energy Star", path: "EnergyStar.svg", name: "Chứng nhận Energy Star (Mỹ)" },
    {shortname: "EPEAT", path: "EPEAT.svg", name: "Chứng nhận EPEAT (Electronic Product Environmental Assessment Tool)" },
    {shortname: "Fairmined", path: "Fairmined.svg", name: "Chứng nhận Fairmined (Vàng khai thác thủ công và khai thác quy mô nhỏ)" },
    {shortname: "Fair Trade", path: "FairTrade.svg", name: "Chứng nhận Thương mại công bằng (Fair Trade)" },
    {shortname: "FCC", path: "FCC.svg", name: "Chứng nhận FCC (Ủy ban Truyền thông Liên bang Mỹ)" },
    {shortname: "FDA", path: "FDAApproval.svg", name: "Chứng nhận FDA (Cục Quản lý Thực phẩm và Dược phẩm Hoa Kỳ)" },
    {shortname: "FSC", path: "FSC.svg", name: "Chứng nhận FSC (Forest Stewardship Council)" },
    {shortname: "FSSC 22000", path: "FSSC22000.svg", name: "Chứng nhận FSSC 22000 (Hệ thống quản lý an toàn thực phẩm)" },
    {shortname: "GFSI", path: "GFSI.svg", name: "Chứng nhận GFSI (Sáng kiến An toàn Thực phẩm Toàn cầu)" },
    {shortname: "GlobalG.A.P.", path: "GlobalG.A.P..svg", name: "Chứng nhận GlobalG.A.P. (Thực hành nông nghiệp tốt toàn cầu)" },
    {shortname: "GMP", path: "GMP.svg", name: "Chứng nhận GMP (Thực hành sản xuất tốt)" },
    {shortname: "GOTS", path: "GOTS.svg", name: "Chứng nhận GOTS (Tiêu chuẩn Toàn cầu về Dệt hữu cơ)" },
    {shortname: "GREENGUARD", path: "GREENGUARD.svg", name: "Chứng nhận GREENGUARD (Chất lượng không khí trong nhà)" },
    {shortname: "HACCP", path: "HACCP.svg", name: "Chứng nhận HACCP (Phân tích mối nguy và Điểm kiểm soát quan trọng)" },
    {shortname: "Halal", path: "Halal.svg", name: "Chứng nhận Halal" },
    {shortname: "HVN CLC", path: "HVNCLC.svg", name: "Chứng nhận hàng Việt Nam chất lượng cao" },
    {shortname: "ISO/IEC 17025", path: "IEC17025.svg", name: "Chứng nhận ISO/IEC 17025 (Yêu cầu chung về năng lực của phòng thí nghiệm thử nghiệm và hiệu chuẩn)" },
    {shortname: "IFS", path: "IFS.svg", name: "Chứng nhận IFS (International Featured Standards)" },
    {shortname: "ISO", path: "ISO.svg", name: "Chứng nhận ISO (Tổ chức Tiêu chuẩn hóa Quốc tế)" },
    {shortname: "Kosher", path: "KosherCertification.svg", name: "Chứng nhận Kosher" },
    {shortname: "LEED", path: "LEEDCertification.svg", name: "Chứng nhận LEED (Lãnh đạo trong Thiết kế và Xây dựng Sinh thái)" },
    {shortname: "VIETNAM ECO LABEL", path: "LOGO_VIETNAM ECO LABEL.svg", name: "Chứng nhận nhãn sinh thái Việt Nam" },
    {shortname: "MSC", path: "MSC.svg", name: "Chứng nhận MSC (Marine Stewardship Council)" },
    {shortname: "NFC", path: "NFC.svg", name: "Chứng nhận NFC (Near Field Communication)" },
    {shortname: "NFPA", path: "NFPA.svg", name: "Chứng nhận NFPA (Hiệp hội Phòng cháy chữa cháy Quốc gia Mỹ)" },
    {shortname: "OCOP", path: "OCOP.svg", name: "Chứng nhận OCOP (Chương trình mỗi xã một sản phẩm)" },
    {shortname: "Oeko-Tex Standard 100", path: "OEKOTEXStandard100.svg", name: "Chứng nhận Oeko-Tex Standard 100 (Vật liệu dệt không gây hại cho sức khỏe)" },
    {shortname: "hữu cơ", path: "OrganicCertification.svg", name: "Chứng nhận hữu cơ" },
    {shortname: "PEFC", path: "PEFC.svg", name: "Chứng nhận PEFC (Programme for the Endorsement of Forest Certification)" },
    {shortname: "REACH", path: "REACHCompliance.svg", name: "Tuân thủ quy định REACH (Đăng ký, Đánh giá, Cho phép và Hạn chế Hóa chất)" },
    {shortname: "RoHS", path: "RoHS.svg", name: "Chứng nhận RoHS (Hạn chế sử dụng một số chất nguy hiểm trong thiết bị điện và điện tử)" },
    {shortname: "RSPO", path: "RSPO.svg", name: "Chứng nhận RSPO (Roundtable on Sustainable Palm Oil)" },
    {shortname: "TCVN", path: "TCVN.svg", name: "Tiêu chuẩn Việt Nam (TCVN)" },
    {shortname: "Underwriters Laboratories", path: "ULCertification.svg", name: "Chứng nhận UL (Underwriters Laboratories)" },
    {shortname: "VietGAHP", path: "VietGAHP (Vietnamese Good Animal Husbandry Practices).svg", name: "Chứng nhận VietGAHP (Thực hành chăn nuôi tốt Việt Nam)" },
    {shortname: "VietGAP", path: "VietGAP (Vietnamese Good Agricultural Practices).svg", name: "Chứng nhận VietGAP (Thực hành nông nghiệp tốt Việt Nam)" }
];

export default certsTemplate;